# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy
      uses: fifsky/ssh-action@master
      with:
        command: |
          ls -a
          cd github-action-test
          git pull
          npm i
          npm run dev
        host: ${{secrets.SERVER_HOST}}
        user: ${{secrets.SERVER_ID}}
        pass: ${{secrets.SERVER_PW}}
