# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
            cd github-action-test
            git pull origin main
            npm i
            npm run dev
          host: ${{secrets.SERVER_HOST}}
          user: ${{secrets.SERVER_ID}}
          pass: ${{secrets.SERVER_PW}}
